### ISSUE TITLE
use ltgt for level style ranges

### ISSUE THREAD

**Issue by dominictarr** [juliangruber/validimir#1]
I recommend using [ltgt](https://github.com/dominictarr/ltgt) which handles the edge cases properly, and is well tested.

What you have here doesn't cover ranges with falsey values.
So, empty string, 0 and false do not get orderings, although they do have defined orders.

It would be simpler if you couldn't use null or undefined as range values, but this is javascript.

**Comment by juliangruber** [comment]
![](http://cdn.memegenerator.es/imagenes/memes/full/2/63/2637613.jpg)

**Comment by juliangruber** [comment]
looking into this now

**Comment by juliangruber** [comment]
fixed in 0.9.1 :)

**Comment by juliangruber** [comment]
with error messages like https://github.com/juliangruber/validimir/blob/master/test/test.js#L132

**Comment by dominictarr** [comment]
looks good!
