### ISSUE TITLE
Catch validator exceptions

### ISSUE THREAD

**Issue by jcollado** [juliangruber/validimir#16]
As a follow up of #14, if would be nice to catch exceptions when validation functions are executed. This way, when multiple validators are chained, the exceptions could be added to the list of errors and the caller could have access not only to the exception information, but also to the results from the other validators in the chain.

**Comment by juliangruber** [comment]
I'm for adding this once we have an extensible api, validation functions that ship with validimir should be solid enough. i'll create a pull request to make all existing checks un-destroyable

**Comment by juliangruber** [comment]
published 1.4.0 with builtin checks that shouldn't fail any more

**Comment by juliangruber** [comment]
feel free to open if you discover otherwise
