### ISSUE TITLE
Numeric Ranges

### ISSUE THREAD

**Issue by 0x00A** [juliangruber/validimir#27]
Support numeric ranges? `v().number({ gt: 50, lt: 100 }, 'must be bla bla bla')(n)`

**Comment by juliangruber** [comment]
would this already work?:

```js
v().number().equal({ gt: 50, lt: 100 })
```

**Comment by 0x00A** [comment]
For convenience it seemed like number should take ltgt args, but separating the primitive type check from the value check is also sensible.
