### ISSUE TITLE
add email check

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/validimir#4]
how many +1s can we get?

@ralphtheninja @hij1nx @dweinstein @deanlandolt

**Comment by ralphtheninja** [comment]
I'll +1 if I don't have to write the regexp for it :D

**Comment by deanlandolt** [comment]
:+1: to the idea...but this is notoriously a bitch -- anything half-decent we can pull off the npm shelf? Obviously doesn't have to be perfect.

**Comment by dweinstein** [comment]
:+1:  FWIW in the past I used the one from `chriso/validator.js` on suggestions from @ekristen

**Comment by ralphtheninja** [comment]
It's a common use case so I'll +1 either way!

**Comment by juliangruber** [comment]
i'd say let's go dead simple, something like https://github.com/regexps/regex-email/blob/master/index.js#L10. There'll be "real" validation of email when you try to send one anyways.

**Comment by deanlandolt** [comment]
LGTM -- too loose is a definitely preferable to too strict.

**Comment by juliangruber** [comment]
https://github.com/juliangruber/validimir/pull/5
